DROP TABLE IF EXISTS HITS;

CREATE TABLE IF NOT EXISTS HITS 
(
                         ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         app VARCHAR,
                         URI VARCHAR(50) NOT NULL,
                         IP VARCHAR(50) NOT NULL,
                         CREATED TIMESTAMP WITHOUT TIME ZONE
);

